### ISSUE TITLE
Externally provided translations break

### ISSUE THREAD

**Issue by bklang** [adhearsion/adhearsion-i18n#6]
Right now adhearsion-i18n specifically expects a rigid format:

``` yaml
en:
  foo_prompt:
    audio: /path/to/foo_prompt.wav
    text: "English translation of the contents of the audio file"
```

However some third-party libraries provide their own internationalizations intended for use with Rails, and do not follow this convention.  adhearsion-i18n should detect this and coerce those values into the text fallback field for SSML.
